### ISSUE TITLE
Escaped quotes in CSS strings are not handled correctly

### ISSUE THREAD

**Issue by ericcornelissen** [ericcornelissen/webmangler#131]
# Bug Report

WebMangler ~~core~~ language-css v0.1.23

## Description

The built-in CSS language plugin has a problem where parts of strings may be mangled if the string's quote appears (escaped) in the string.

## Steps to Reproduce

Mangle the following CSS using the CSS Language Plugin and the CSS Variable Mangler using the pattern `[a-z]+`. Both `--bar` and `--baz` will be mangled even though they're in a string.

```css
div {
  content: "var(--foo)";
  content: "foo \" var(--bar) ";
  content: 'foo \' var(--baz) ';
}
```
