### ISSUE TITLE
Comments in CSS may be mangled if the comment contain a newline 

### ISSUE THREAD

**Issue by ericcornelissen** [ericcornelissen/webmangler#222]
# Bug Report

- Package(s): [language-css](https://github.com/ericcornelissen/webmangler/tree/f35f6bf9c90206da05e64ab6e10902c3a9fe538e/packages/language-css)
- Version(s): `v0.1.26`

## Description

When mangling a CSS stylesheets with comments, the `language-css` plugin might accidentally mangle in comments if the comment contains a newline.

## Proof of Concept

1. Have a CSS file with mangle-able CSS in a CSS comment (`/* */`). For example:

   ```css
   .cls-foo {
     color: purple;
   }

   /*
   .cls-bar {
     color: orange;
   }
   */
   ```

2. Run [WebMangler CLI (version `0.1.6`)](https://github.com/ericcornelissen/webmangler/tree/f35f6bf9c90206da05e64ab6e10902c3a9fe538e/packages/cli) with [WebMangler Core (version `0.1.24`)](https://github.com/ericcornelissen/webmangler/tree/f35f6bf9c90206da05e64ab6e10902c3a9fe538e/packages/core) and the default mangler plugins & default language plugins (at the exact versions found in the [WebMangler Core `package.json`](https://github.com/ericcornelissen/webmangler/blob/f35f6bf9c90206da05e64ab6e10902c3a9fe538e/packages/core/package.json#L33-L39)).

3. Observe that the comments have been mangled. For the example above:

   ```css
   .a {
     color: purple;
   }

   /*
   .b {
     color: orange;
   }
   */
   ```
