### ISSUE TITLE
CssLanguagePlugin does not mangle classes in attribute selectors

### ISSUE THREAD

**Issue by ericcornelissen** [ericcornelissen/webmangler#240]
# Bug Report

- Package(s): [language-css](https://github.com/ericcornelissen/webmangler/tree/0ff341364c26101b3f4cdb4774764335b32c3c45/packages/language-css)
- Version(s): `0.1.27`

## Description

The `CssLanguagePlugin` won't mangle CSS classes in attribute selectors (e.g. `[class="cls-foo cls-bar"]`). This is because it's missing support for [the `multi-value-attributes` expression type](https://github.com/ericcornelissen/webmangler/blob/0ff341364c26101b3f4cdb4774764335b32c3c45/packages/types/src/options.ts#L68). As such, this bug applies more generally to any plugin that relies on the `multi-value-attributes` expression type.

## Actual Behaviour

1. Have a CSS with a attribute selector for the `class` attribute. For example:

   ```css
    .cls-foo {
      color: red;
    }
    [class="cls-foo"] {
      color: purple;
    }
   ```

2. Run [WebMangler CLI (version `0.1.6`)](https://github.com/ericcornelissen/webmangler/tree/f35f6bf9c90206da05e64ab6e10902c3a9fe538e/packages/cli) with [WebMangler Core (version `0.1.24`)](https://github.com/ericcornelissen/webmangler/tree/f35f6bf9c90206da05e64ab6e10902c3a9fe538e/packages/core) and at least [WebMangler CSS Language Plugin version `0.1.27`](https://github.com/ericcornelissen/webmangler/tree/0ff341364c26101b3f4cdb4774764335b32c3c45/packages/language-css) and [WebMangler CSS Class Mangler version `0.1.23`](https://github.com/ericcornelissen/webmangler/tree/0ff341364c26101b3f4cdb4774764335b32c3c45/packages/mangler-css-classes).

3. Observe that the CSS file isn't mangled completely. For the example above:

   ```css
    .a {
      color: red;
    }
    [class="cls-foo"] {
      color: purple;
    }
   ```

## Expected Behaviour

The mangled CSS looks something like:

```css
.a {
  color: red;
}
[class="a"] {
  color: purple;
}
```
