### ISSUE TITLE
Mangling CSS values with nested functions

### ISSUE THREAD

**Issue by ericcornelissen** [ericcornelissen/webmangler#98]
# Bug Report

## Description

The [CSS Language Plugin](https://github.com/ericcornelissen/webmangler/tree/cc6ced997bb1cf52ed76fdeab94c0e0e17edad48/packages/core/src/languages/css) seems to be unable to mangle in CSS values if nested functions are used.

## Reproduce

1. Generate expressions using [the CSS values expression factory](https://github.com/ericcornelissen/webmangler/blob/cc6ced997bb1cf52ed76fdeab94c0e0e17edad48/packages/core/src/languages/css/css-values.ts) using: `cssDeclarationValueExpressionFactory({ prefix: "var\\(--",  suffix: "\\)"})`.
2. Match the generated expressions against the following CSS with the pattern `[a-z]+`:
    ```css
    div {
      content: var(--foo);
      margin: minmax(var(--bar));
    }
    ```
3. Observe that only "foo" is returned.
